// Generated by `zfa setup`. Do not edit; re-run `zfa tdd init` to refresh.
import 'package:flutter_test/flutter_test.dart';
import 'package:zuraffa_dashboard/app.dart';

void main() {
  group('bootstrap smoke', () {
    test('the app module and DI container can be constructed', () {
      // The generated app module (lib/app.dart) exposes a zfa-generated
      // DI container named after the app: ZuraffaDashboardContainer. Constructing
      // it without throwing proves the DI graph is satisfiable at runtime
      // — the day-zero precondition for any TDD work on the generated app
      // (spec 041 FR-001; the container is emitted by `zfa setup`,
      // issue #626).
      final container = ZuraffaDashboardContainer();
      expect(container, isNotNull);
    });
  });
}
