// Generated by zfa — bootstrap DI index (issue #626).
//
// Day-zero empty graph: `setupDependencies` registers nothing until
// `zfa di <Entity>` / `zfa make <Entity> --with=di` generate the real
// registrations (they append into this function). `zfa app shell` reads
// this barrel to wire the generated entrypoint.
import 'package:zuraffa/zuraffa.dart';

void setupDependencies(GetIt getIt) {}
