// Generated by zfa — bootstrap routing index (issue #626).
//
// Day-zero empty route table: `getAllRoutes()` returns no routes until
// `zfa route <Entity>` / `zfa make <Entity> --with=route` generate the
// route modules (they regenerate this index). `zfa app shell` reads
// this barrel to wire the GoRouter.
import 'package:go_router/go_router.dart';

List<RouteBase> getAllRoutes() => const [];
