// Generated by zfa — day-zero app module (issue #626).
//
// This is the app surface the day-zero smoke test asserts (spec 041
// FR-001): a zfa-generated DI container whose symbol derives from the
// app name (`zuraffa_dashboard` -> ZuraffaDashboardContainer). The bootstrap graph is empty —
// `zfa di <Entity>` / `zfa make <Entity> --with=di` populate it, and
// `zfa app shell` upgrades the minimal shell with the generated routing
// tree. Constructing the container must never throw, so `flutter test`
// is green from the first minute (spec 041 FR-006).
import 'package:zuraffa_flutter/zuraffa_flutter.dart';

/// Bootstrap DI container for `zuraffa_dashboard`.
///
/// Day zero the dependency graph is empty: [di] exposes the GetIt
/// registry the zfa-generated `setupDependencies(GetIt getIt)` wires
/// into, and [bootstrap] registers nothing until entities exist.
/// `zfa app shell` upgrades this minimal module into the generated app
/// shell; construction stays side-effect-free so the smoke test can
/// assert it unconditionally.
class ZuraffaDashboardContainer {
  /// The dependency-injection registry backing this container.
  ///
  /// The same GetIt instance the generated DI barrel wires into. Empty
  /// until `zfa di` / `zfa make --with=di` populate the graph.
  final GetIt di = GetIt.instance;

  /// Bootstrap the (day-zero empty) dependency graph.
  ///
  /// A deliberate no-op until the DI generators upgrade this module;
  /// calling it must never throw (spec 041 FR-001).
  void bootstrap() {}
}
